import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/ui/common/header";
import Sidebar from "@/ui/common/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "data from tarkov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header></Header>
        <div className="container flex-row flex mx-auto mb-16 h-full relative mt-4">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
